### ISSUE TITLE
Installing globally yields "permission denied" errors due to sass-cache

### ISSUE THREAD

**Issue by baschny** [bootstrap-email/bootstrap-email#102]
If I install this as root globally (i.e. in a Dockerfile), a regular user is not able to use it, due to the sass-cache being expected to be relative to the installation directory.

Error:
```
$ echo "<head><style>test</style></head><body><h1>Test</h1></body>" | bootstrap-email 
Traceback (most recent call last):
	11: from /usr/bin/bootstrap-email:23:in `<main>'
	10: from /usr/bin/bootstrap-email:23:in `load'
	 9: from /usr/lib/ruby/gems/2.5.0/gems/bootstrap-email-1.0.0.alpha2.1/bin/bootstrap-email:2:in `<top (required)>'
	 8: from /usr/lib/ruby/gems/2.5.0/gems/bootstrap-email-1.0.0.alpha2.1/bin/bootstrap-email:2:in `require_relative'
	 7: from /usr/lib/ruby/gems/2.5.0/gems/bootstrap-email-1.0.0.alpha2.1/lib/bootstrap-email/bootstrap_email_cli.rb:87:in `<top (required)>'
	 6: from /usr/lib/ruby/gems/2.5.0/gems/bootstrap-email-1.0.0.alpha2.1/lib/bootstrap-email/bootstrap_email_cli.rb:87:in `new'
	 5: from /usr/lib/ruby/gems/2.5.0/gems/bootstrap-email-1.0.0.alpha2.1/lib/bootstrap-email/compiler.rb:17:in `initialize'
	 4: from /usr/lib/ruby/gems/2.5.0/gems/bootstrap-email-1.0.0.alpha2.1/lib/bootstrap-email/compiler.rb:41:in `build_premailer_doc'
	 3: from /usr/lib/ruby/gems/2.5.0/gems/bootstrap-email-1.0.0.alpha2.1/lib/bootstrap-email/sass_cache.rb:7:in `compile'
	 2: from /usr/lib/ruby/gems/2.5.0/gems/bootstrap-email-1.0.0.alpha2.1/lib/bootstrap-email/sass_cache.rb:23:in `compile'
	 1: from /usr/lib/ruby/gems/2.5.0/gems/bootstrap-email-1.0.0.alpha2.1/lib/bootstrap-email/sass_cache.rb:61:in `compile_and_cache_scss'
/usr/lib/ruby/gems/2.5.0/gems/bootstrap-email-1.0.0.alpha2.1/lib/bootstrap-email/sass_cache.rb:61:in `mkdir': Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.5.0/gems/bootstrap-email-1.0.0.alpha2.1/.sass-cache (Errno::EACCES)
```

Better would be to use `$HOME/.sass-cache` for sass caching (instead of hardcoded `CACHE_DIR = File.expand_path('../../.sass-cache', __dir__)`).

**Comment by stuyam** [comment]
Ah interesting. Interested about your thoughts on the `$HOME` variable, im not sure how that works and how that would affect other installations. The sass cache stuff is sticky for sure open to suggestions on it 👍

**Comment by baschny** [comment]
Overall, storing the cache inside the bootstrap-email installation directory doesn't seems right to me conceptually.

Using `$HOME` was just an idea on how other software does that, because an user can always write files to its `$HOME`. But I would also be happy to be able to have either a cmd-line switch or an `ENV` variable to be able to override the location of the cache-directory.

**Comment by jasonadamyoung** [comment]
I just ran into this in production as well (my production docker container in kubernetes). I definitely think writing to the where the gems are is probably not the best strategy (particularly for most production deployments)

I just did a 

```
    CACHE_DIR = File.join(Dir.tmpdir,'.sass-cache')
```

to get it working for my use.  

It seems like putting it into `tmp` is the best course of action here overall, outside of letting it be specified in initialization.

**Comment by stuyam** [comment]
I made some changes to the sass cache file location. For rails it now puts it in the rails `tmp/cache` directory. If it's not running in Rails it will check if `pwd` is writable, if it is it will use that directory, else it will write to `Dir.tmpdir`.

I have the code on master so you can pull it into your gemfile like this and give it a test to see if it works. Then I will release a new version if that seems to work for people.
```ruby
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem 'bootstrap-email', github: 'bootstrap-email/bootstrap-email', branch: 'master'
```

**Comment by jasonadamyoung** [comment]
@stuyam Looks fine/works great for me - both local docker dev and in production. My environment is Rails, and I dig the specificity of Rails.root/tmp/cache/bootstrap-email here.  

Thanks for getting that added in! 🎉

**Comment by stuyam** [comment]
In the latest alpha release v1.0.0.alpha3 it will pick better sass cache locations as mentioned above. You can also now configure where you want the sass cache to be stored. Here is an example:
```ruby
BootstrapEmail.configure do |config|
  # Defaults to ./.sass-cache or ./tmp/cache/bootstrap-email/.sass-cache in rails
  config.sass_cache_location = [File.expand_path('some/folder', __dir__)]
end
```
Here is more info on configuration: https://v1.bootstrapemail.com/docs/configure
Hope this solves your problems 👍
