### ISSUE TITLE
"New css file cached" message appears in output

### ISSUE THREAD

**Issue by sriv1211** [bootstrap-email/bootstrap-email#104]
### Describe the problem:
When running `bootstrap-email /app/layouts/order.html > /app/output/order.html` with `bootstrap-email-1.0.0.alpha2.1`

I see the following message `New css file cached for bootstrap-email` at the top of the file

```
New css file cached for bootstrap-email
New css file cached for bootstrap-head
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head>
    <!-- Compiled with Bootstrap Email version: 1.0.0.alpha2.1 -->
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  ...
```

**Comment by sriv1211** [comment]
Perhaps outputing to stderr instead over here?
https://github.com/bootstrap-email/bootstrap-email/blob/badb4311d86a2671dfe469539853aa51998137d1/lib/bootstrap-email/sass_cache.rb#L64

**Comment by baschny** [comment]
> Perhaps outputing to stderr instead over here?
> 
> https://github.com/bootstrap-email/bootstrap-email/blob/badb4311d86a2671dfe469539853aa51998137d1/lib/bootstrap-email/sass_cache.rb#L64

Very important thing, as we are running this in our containers, and every new container gets a new cache and thus we get this debug output in this situation.

**Comment by stuyam** [comment]
In the latest alpha release v1.0.0.alpha3 it will no longer log when sass is cached when you are using the CLI that outputs the compiled code directly.
You can also use the new config to predictable enable or disable that log line.
```ruby
BootstrapEmail.configure do |config|
  # Defaults to true, is disabled during CLI commands that output to standard out
  config.sass_log_enabled = true
end
```
Here is more info on configuration: https://v1.bootstrapemail.com/docs/configure
Hope this solves your problems, it should _just work_ 👍
