### ISSUE TITLE
Sass @import not working in bootstrap-email.config.scss

### ISSUE THREAD

**Issue by cernyjakub** [bootstrap-email/bootstrap-email#105]
I am trying to integrate the alpha version into my Rails app. I have added some custom tweaks into `boostrap-email.config.scss` file in my `app/assests/stylesheets` folder.

All works fine, but when I tried to use sass `@import` to load my color variables from other file (used in web CSS style), system tells me _Error: File to import not found or unreadable_. The file is in the same folder - it seems to me Sass is not having that folder in its load path... Any advice? I think having the option to re-use color definitions from normal web stylesheets would be very cool.

_this is moved from Discussions following suggestion from @stuyam_

**Comment by stuyam** [comment]
If you download the latest release v1.0.0.alpha3 you will be able to configure a path to the directory of files that you want added to the sass load path.
Something like this:
```ruby
BootstrapEmail.configure do |config|
  config.sass_load_paths = [File.expand_path('some/folder', __dir__)]
end
```
You can read more about the new way to config here: https://v1.bootstrapemail.com/docs/configure
Let me know if you have any issues, hope this solves your problem 👍

**Comment by cernyjakub** [comment]
Perfect! Thanks a lot!

j
