### ISSUE TITLE
CLI: Mail in UTF-8 treated as non UTF-8

### ISSUE THREAD

**Issue by timdebelder007** [bootstrap-email/bootstrap-email#114]
#### compiler: CLI

When I compile my email containing special characters the compiled mail formats the characters in a non UTF-8 formatting.

**source version**
`<div class="col">Test for special characters: é è ç à ù</div>`
**compiled version**
`<td class="col" style="line-height: 24px; font-size: 16px; min-height: 1px; font-weight: normal; padding-right: 30px; margin: 0;" align="left" valign="top">Test for special characters: ├® ├¿ ├º ├á ├╣</td>`

Is there a way to tell the compiler to return an UTF-8 version result?
Or is there a meta tag that tells the compiler which he needs to use? (`<meta http-equiv="Content-Type" content="text/html; charset=utf-8">`)

When i use the online editor i get the requested result.

greetz

Tim

**Comment by stuyam** [comment]
Just tested locally and this is now working correctly in the v1+ and latest versions
