### ISSUE TITLE
Editor send test email with the wrong html

### ISSUE THREAD

**Issue by Yobikap** [bootstrap-email/bootstrap-email#116]
Hi,

In the editor when I try to send myself an email, I am getting the wrong rendered html in my inbox.

Actually I am expecting something with table as source code.

Reproduction steps:
1. Go to https://app.bootstrapemail.com/editor
2. Click on Test in the right corner
3. Fill out your email address and hit Send
4. Check the result in your email box
5. Check de source code of your email
6. Go back to https://app.bootstrapemail.com/editor
7. Click on HTML tab, and compare the source code of your email with the contents in the HTML tab in editor

**Comment by stuyam** [comment]
You are saying the code you wrote in the editor (and not the compiled code) is being sent when using the test button in the editor? I'll have to check on that and make sure it is working properly, it's possible something got messed up there recently when I added support for using the different versions of bootstrap email in the editor. Thanks 👍

**Comment by dannycorder** [comment]
Hi, 

Not sure if this is related.

I haven't checked the exact HTML but I noticed that the rendered version in the online editor looked great.  When I sent the test e-mail it looked very different and all the spacing had disappeared.

Regards,
Danny

**Comment by stuyam** [comment]
@Yobikap and @dannycorder which version of Bootstrap Email are you rendering with in the editor: `v0.3.4` or `v1.0.0.alpha3.1`? My hunch is there is a bug where the email is being sent rendered with the wrong version.

**Comment by dannycorder** [comment]
Hi, I tried the alpha as the current version wasn't rendering content properly at all in the preview.

I haven't spent enough time diagnosing though, I'll let you know if I spot anything useful.

Regards,
Danny

**Comment by stuyam** [comment]
Fixed! Thanks for the helpful comments @dannycorder and for opening the issue @Yobikap. Hope it works better for you now, enjoy.
