### ISSUE TITLE
Linked images don't work if we use Rails helpers

### ISSUE THREAD

**Issue by FarazPatankar** [bootstrap-email/bootstrap-email#15]
I was trying to link the social media icons in the footer of my emails to the social media account but it does not work. I tried all combinations of `link_to` and `image_tag`. I also tried using an `<a>` tag and an `<img>` tag but with an `image_path` to generate the asset pipeline URL. It still fails to work.

But, if I do something that does not involve a Rails helper:
`<a href="www.google.com"><img src="https://bootstrapemail.com/img/icons/logo.png"></a>`

It works.

I need to use at least some Rails helper in order to properly generate the links to my image. Any suggestions?

Also, such links work in normal emails. They stop working if we use `make_bootstrap_mail`.

**Comment by stuyam** [comment]
What do you mean by it does not work? You get an error? The url isn't correct? The image tag is missing? Can you give me some more information?

Also when it comes to emails you should always be using `image_url` and not `image_path` because `_url` includes the host of your site where `_path` is a relative path which will not work in an email client.

**Comment by FarazPatankar** [comment]
Sorry about that. The image renders correctly but the link tag does not. Basically I see `<img src"IMAGE_URL">` instead of `<a href="LINK"><img src="IMAGE_URL"></a>`

**Comment by stuyam** [comment]
Can you show example code of what you are trying?

**Comment by FarazPatankar** [comment]
Like I said, I have tried several things. I'll add some snippets here.
```
# Attempt 1
<%= link_to 'https://www.google.com/' do %>
  <%= image_tag("facebook_icon.png", height: '20', width: '20', class: "float-right pl-2") %>
<% end %>

# Attempt 2
<%= link_to image_tag("facebook_icon.png", height: '20', width: '20', class: "float-right pl-2"), 'https://www.google.com/' %>

# Attempt 3
<a href="https://www.google.com/">
  <%= image_tag("facebook_icon.png", height: '20', width: '20', class: "float-right pl-2") %>
</a>

#Attempt 4

**Comment by FarazPatankar** [comment]
@stuyam Have you had the time to check this out?

**Comment by j540** [comment]
I am also having this error. I imagine a lot of users want to have a logo image with a link around it, so this is probably a common issue.

**Comment by j540** [comment]
I've come across a similar but possibly distinct issue, and found a solution.

This doesn't work. The a tag will be stripped:
<a href='https://www.google.com' ><img class='mx-auto mt-4 mb-3' width="100" height="27" src="https://example.com/img.png" ></a>

Moving the classes off of the image onto the a tag fixes the issue:
  <a href='https://www.google.com' class="mx-auto mt-4 mb-3" ><img  width="100" height="27" src="https://example.com/img.png" ></a>

**Comment by stuyam** [comment]
Just tested this in the latest bootstrap email release v1.1.2 and it seems to work fine now 👍
