### ISSUE TITLE
More than one Handlebars in <a> tag being URL encoded

### ISSUE THREAD

**Issue by PneutronixJeremy** [bootstrap-email/bootstrap-email#184]
Hello again @stuyam !
This was fixed, but came up again.
It seems now when we have two handlebars references in a <a> tag, it url encodes the seconds one. Do we need to adjust the regex to allow multiple matches?

Here is an example of the issue:

``` <a href="https://{{Domain}}/{{shortGuid MessageGuid}}"> ```
Becomes:
``` <a href="[https://{{Domain}}/%7B%7BshortGuid%20MessageGuid%7D%7D"> ```

Any suggestions? Sorry we didn't catch this earlier.

_Originally posted by @PneutronixJeremy in https://github.com/bootstrap-email/bootstrap-email/discussions/131#discussioncomment-2787149_

**Comment by stuyam** [comment]
Yup definitely a bug!

**Comment by ComtelJeremy** [comment]
Hello @stuyam. Thanks a million for this fix. We haven't tried it yet (have to revert our workaround), but just checking... we were getting %20 for spaces in the handlebars too (the second one for sure). This should stop _all_ encoding in the handlebars, correct?

**Comment by stuyam** [comment]
Correct! It won't encode anything in the handlebars as you can see in the spec here: https://github.com/bootstrap-email/bootstrap-email/blob/449975d8587a6c701c2e4806499d5c3473c0e731/spec/converters/support_url_tokens_spec.rb#L24-L42

The way it works is it finds what looks to be URL encoded handlebar notations and then it URL _decodes_ everything inside of that so it gets reverted.

**Comment by ComtelJeremy** [comment]
I looked at the commit and saw that spec (but I'm a dotnet guy, so I wanted to be sure).

Thanks again for all your work on this library. We appreciate you!
