### ISSUE TITLE
d-none and d-lg-inline are not working on iOS Phone

### ISSUE THREAD

**Issue by urthling** [bootstrap-email/bootstrap-email#185]
### What version of Bootstrap Email are you using?

v1.1.6

### How are you compiling?

Online Editor

### Describe your issue

d-none and d-lg-inline are not working on iOS -- both iPAD (landscape) and iPhone (portrait) should be considered Mobile

Both of these appear on my phone:
```
<div class="d-lg-none">Hidden on Desktop</div>
<div class="d-none d-lg-inline">Hidden on Mobile</div>
```

Both of these do work in terms of one hidden and one showing, however, my phone considers itself a desktop and not mobile.
```

<div class="row d-lg-none">
.......

<div class="row d-none d-lg-inline">
.....

```

**Comment by stuyam** [comment]
I just tested this in the online editor and sent a test email to myself and it worked on my iPhone 13 runnings iOS 15.5 in Apple Mail. Try sending this as a test email to yourself via the online editor and please verify the type of iPhone and iOS version you are running that you are seeing this on. Thank you 🙏 
```html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>
  <body class="bg-light">
    <div class="d-lg-none">Hidden on Desktop</div>
	<div class="d-none d-lg-inline">Hidden on Mobile</div>
  </body>
</html>

```
