### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by mashakos** [bootstrap-email/bootstrap-email#187]
### What version of Bootstrap Email are you using?

1.1.6

### How are you compiling?

rails

### Describe your issue

After a bit of trial and error I have found the following:

- The Bootstrap class " d-xs-none" breaks the grid entirely.
- When using group lists, adding the class " align-items-center" to any list-group-item results in the text within each element being replaced with a space and the list items have a strange yellow background
- Body bg colour seems to be green by default not sure why

**Comment by stuyam** [comment]
Bootstrap and Bootstrap Email don't have the exact same classes. For example `d-xs-none` is not a valid class in Bootstrap Email. For responsive on small and up you want `d-none` and for desktop and above you want `d-lg-none`.
