### ISSUE TITLE
Possibility to add input groups?

### ISSUE THREAD

**Issue by SoggyShotz** [bootstrap-email/bootstrap-email#19]
I am using input groups for stylizing and was wondering if/how hard it would be to implement them into this.

Excellent work so far!

**Comment by stuyam** [comment]
Well they were never implemented because of email support for input elements. I am curious your use case? Are you trying to make an element look like an input or something?

**Comment by SoggyShotz** [comment]
Yes, just for easily transitioning between input and view forms for the user. Simply styling preferences. Makes sense to not be included if it bugs out the email program.

**Comment by SoggyShotz** [comment]
After some more browsing it seems there's some trickery available to display rounded corners in Outlook.

https://gist.github.com/elidickinson/9424116

If I knew how to implement these things I would definitely help you out but for now I'm just stuck researching and using.

**Comment by stuyam** [comment]
Not on the roadmap
