### ISSUE TITLE
Email part 'text/plain' not found 

### ISSUE THREAD

**Issue by brunaportugal** [bootstrap-email/bootstrap-email#195]
### What version of Bootstrap Email are you using?

1.1.6

### How are you compiling?

Ruby on Rails 

### Describe your issue

I updated the bootstrap-email gem from the 0.3.4 to the 1.1.6 version. Before, I was able to easily access the text/plain part by calling the #text_part method, and also to preview the text/plain emails without creating specific plain text templates for them. Since the update I can't seem to do that anymore. Am I missing something or is this functionality not there anymore?

Thank you!

**Comment by stuyam** [comment]
Yeah I think you a right about the plain text option missing in 1+ and this is definitely an oversight. We are still using premailer under the covers which supports outputting a plaintext version so we should be able to support it but we don't currently.

**Comment by stuyam** [comment]
Working on adding plaintext support in BSE v1+ 🎉

**Comment by brunaportugal** [comment]
Amazing! Thank you, Stuart ☺️

**Comment by brunaportugal** [comment]
Amazing! Thank you, Stuart ☺️

**Comment by stuyam** [comment]
I just released this in v1.3.0 https://github.com/bootstrap-email/bootstrap-email/releases/tag/1.3.0. Would love if you gave this a try in your rails app and let me know if it worked for you 🎉 Please keep me posted thank you and enjoy.

**Comment by brunaportugal** [comment]
Hi @stuyam, thanks again for working on this issue so fast! I updated the gem version in my application, and now I have the plain text support (yay 🎉), but unfortunately after the update my HTML versions are broken 😞 as soon as I switch the version back to 1.2.0 it works again.

**Comment by pwoltman** [comment]
I have the same issue as @brunaportugal - updating to 1.3.0 results in the HTML being rendered as plain text.  Reverting to 1.2.0 restores expected HTML rendering

**Comment by stuyam** [comment]
There was some weird multipart issues introduced in 1.3.0 that should be now fixes in 1.3.1, see #199 for more details 🎉
