### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by SoggyShotz** [bootstrap-email/bootstrap-email#20]
The finalized email being viewed from Outlook Professional Plus 2016 is not rendering correctly. I am able to see the view fine in my Rails email previews and verified all my tags are closed. Have I missed something or has is there a potential block for this version? Even when selecting view in browser from the email client it looks the same as the email.

Cards are not showing rounded corners, text centering is not working in the card-header, and when viewing the source from Outlook it seems that there are tables inserted within my tbody. 

I assume that it's using tables within tables to create the alignment in the html, but not sure about the other things.

**Comment by SoggyShotz** [comment]
So after working on multiple emails I decided to copy the default from the site and email it to myself. I'm not sure if it's an issue with Outlook 2016 but the text-center seems to be failing. Snippet from email provided.


![default](https://user-images.githubusercontent.com/42212529/43902382-f059e448-9bb7-11e8-9858-0738ee0b06ce.png)

**Comment by stuyam** [comment]
I can look into this further, but most versions of Outlook do not support rounded corners and that is just a limitation. Text centering seems to be broken though it sounds like

**Comment by silverarm** [comment]
I've been working on a php clone  and have got it running  (yesterday) and also had this similar error.

The solution  (in php) example is to apply an align tag against nodes with the text-left, text-right, and text-center tags. 

You end up with
```html
<h4 class="text-center" 
![styling-outlook-bootstrapemail](https://user-images.githubusercontent.com/2063840/43925301-d47940b8-9c1e-11e8-897d-b7cc72490942.jpg)
align="center" style="margin-top: 0; margin-bottom: 0; font-weight: 500; color: inherit; vertical-align: baseline; font-size: 24px; line-height: 28.8px; text-align: center !important;">Make expensing business rides easy</h4>```


Heres a PHP Snippet - ignore the max loop stuff just safety checks that i get out of the loops.
But you should be able to get the gist....

```php
while ($exists && $maxLoop < 40) {
            $maxLoop += 1;

            $nodes = $this->xpath->query('//*[contains(concat(" ", @class, " "), " text-center ") and not(contains(@align, "center")) ]');
            if (!isset($nodes[0])) {
                $exists = false;
            } else {
                $item = $nodes[0];
                $removeClass = 'text-center';
                $class = $item->getAttribute("class");
                $newClass = preg_replace("/" . preg_quote($removeClass) ."/i", '', $class);
                //$item->setAttribute("class", $newClass);
                $item->setAttribute("align", 'center');
            }
        }
        $exists = true;
        while ($exists && $maxLoop < 40) {
            $maxLoop += 1;

            $nodes = $this->xpath->query('//*[contains(concat(" ", @class, " "), " text-right ") and not(contains(@align, "right")) ]');
            if (!isset($nodes[0])) {
                $exists = false;
            } else {
                $item = $nodes[0];
                $removeClass = 'text-right';
                $class = $item->getAttribute("class");
                $newClass = preg_replace("/" . preg_quote($removeClass) ."/i", '', $class);
                //$item->setAttribute("class", $newClass);
                $item->setAttribute("align", 'right');
            }
        }
        $exists = true;
        while ($exists && $maxLoop < 40) {
            $maxLoop += 1;

            $nodes = $this->xpath->query('//*[contains(concat(" ", @class, " "), " text-left ") and not(contains(@align, "left")) ]');
            if (!isset($nodes[0])) {
                $exists = false;
            } else {
                $item = $nodes[0];
                $removeClass = 'text-left';
                $class = $item->getAttribute("class");
                $newClass = preg_replace("/" . preg_quote($removeClass) ."/i", '', $class);
                //$item->setAttribute("class", $newClass);
                $item->setAttribute("align", 'left');
            }
        }
```

**Comment by silverarm** [comment]
Might need to wrap the Apple PAy text in a float left to get it to behave

```html
 <img class="pr-2 float-left" height="20" width="32" src="https://s3.amazonaws.com/lyft.zimride.com/images/emails/credit_icons/cc_apple_pay.png"/><div class = "float-left">Apple Pay (MasterCard)</div>```

**Comment by SoggyShotz** [comment]
@silverarm assigning the align="center" fixed the text-center issue for me in the email. Thanks for that suggestion. I hadn't attempted to put the inline styling since I wasn't sure if it would just break the system with it doing inline styling already.

**Comment by stuyam** [comment]
No longer relevant to latest releases of v1+
