### ISSUE TITLE
bg_transparent class gives green background and not transparent

### ISSUE THREAD

**Issue by ALPDM** [bootstrap-email/bootstrap-email#202]
### What version of Bootstrap Email are you using?

1.3.1

### How are you compiling?

Online Editor

### Code example

 `<body class="bg-transparent">....` 

### Describe your issue

Background becomes green and not transparent. Tested in online editor, iOS mail, OSX mail, iPadOS mail.

Adding `body { background-color: transparent; }` and similar workarounds do not work. They result in `bgcolor="#ffffff"` 

This is especially annoying when viewing email on devices in dark mode.

**Comment by whirledsol** [comment]
I can reproduce this.
The class results in ```bgcolor='"transparent"'``` which seems to render green on most browsers. Removing or blanking ```bgcolor=""``` seems to work.

**Comment by stuyam** [comment]
Good call on this, this is now fixed in the latest v1.4.1 release: https://github.com/bootstrap-email/bootstrap-email/releases/tag/1.4.1
