### ISSUE TITLE
Cannot download compiled "Simple Card" template code

### ISSUE THREAD

**Issue by DavidMetcalfe** [bootstrap-email/bootstrap-email#203]
### What version of Bootstrap Email are you using?

N/A

### How are you compiling?

Online

### Code example

N/A

### Describe your issue

The [Simple Card](https://app.bootstrapemail.com/templates/free-simple-card) template does not provide a compiled code download despite being signed in to GitHub. A new window is opened with each click but nothing happens after that.

**Comment by stuyam** [comment]
This seems to be fixed now
