### ISSUE TITLE
undefined method `scan' inside head style converter

### ISSUE THREAD

**Issue by Yaty** [bootstrap-email/bootstrap-email#210]
### What version of Bootstrap Email are you using?

1.3.1

### How are you compiling?

Rails

### Describe your issue

Hello,

First, thanks for this library and your work! It helped me a lot.

I'm opening this issue to report an error we had twice today in production and I have a really hard time reproducing it:

```
undefined method `scan' for nil:NilClass
bootstrap-email (1.3.1) lib/bootstrap-email/converters/head_style.rb:24 purged_css_from_head |  
bootstrap-email (1.3.1) lib/bootstrap-email/converters/head_style.rb:16 bootstrap_email_head |  
bootstrap-email (1.3.1) lib/bootstrap-email/converters/head_style.rb:8 build |  
bootstrap-email (1.3.1) lib/bootstrap-email/converters/base.rb:14 build |  
bootstrap-email (1.3.1) lib/bootstrap-email/compiler.rb:104 configure_html |  
bootstrap-email (1.3.1) lib/bootstrap-email/compiler.rb:36 perform_html_compile |  
bootstrap-email (1.3.1) lib/bootstrap-email/compiler.rb:24 perform_multipart_compile |  
bootstrap-email (1.3.1) lib/bootstrap-email/rails/mail_builder.rb:50 generate_alternative_part |  
bootstrap-email (1.3.1) lib/bootstrap-email/rails/mail_builder.rb:38 generate_html_part_replacement |  
bootstrap-email (1.3.1) lib/bootstrap-email/rails/mail_builder.rb:18 perform |  
bootstrap-email (1.3.1) lib/bootstrap-email/rails/mail_builder.rb:9 perform |  
bootstrap-email (1.3.1) lib/bootstrap-email/rails/action_mailer.rb:7 bootstrap_mail
```

Looks like `BootstrapEmail::SassCache.compile('bootstrap-head', @config)` does not correctly return the content of `bootstrap-head.scss` which contains `/*! allow_purge_after */ `. Thus the `undefined method scan for nil:NilClass` error. Maybe the cache is returning nothing? It is not failing every time so I'm not sure what's going on.

We don't have any fancy configuration of `bootstrap-email`, we use the default one. We only customized a bit `bootstrap-email.scss` which is inside `./app/assets/stylesheets`.

I will try to dig more into this issue in the next days, I hope to find the cause of this! You maybe have some ideas? I'd be more than happy to contribute to fix this issue :)

Hugo

**Comment by stuyam** [comment]
Always open to code contributions that sounds great! If not I will get around to looking into it at some point 👍

**Comment by Yaty** [comment]
I investigated a bit more today into this issue: this is only happening when calling `bootstrap_mail` multiple times. I can reproduce it by creating many threads and compiling bootstrap-head. Sometime the css returned is an empty string.

``` ruby
    it 'is thread safe' do
      config = BootstrapEmail::Config.new
      FileUtils.rm_rf(Dir.glob("#{config.sass_cache_location}/*"))
      SassC.load_paths << config.sass_load_paths

      10.times do
        threads = []

        10.times do
          threads << Thread.new do
            css = BootstrapEmail::SassCache.compile('bootstrap-head', config)
            expect(css.length).not_to eq(0)
          end
        end

        threads.each(&:join)
      end
    end
```

I guess this creates some race condition issue where the cache is not ready, or not fully ready. I think in order to fix this we would need to add some locks into the caching class, or we can move to in-memory caching. What do you think?

**Comment by krzcho** [comment]
The solution is to add
/*! allow_purge_after */
at the end of your bootstrap-head.scss

**Comment by Yaty** [comment]
Thanks for your input @krzcho! I'm already using the default `bootstrap-head.scss`, and this one is containing` /*! allow_purge_after */`. I'm not even sure we can overwrite `bootstrap-head.scss`? 

I'm not so much used to bootstrap-mail code but I think your fix will prevent any errors to be raised, so the email will be sent without styles from  `bootstrap-head.scss`? I prefer to have an error so I can retry to send the email later like it is now with the correct styles than sending weird looking emails.
