### ISSUE TITLE
Badge component is not being compiled correctly

### ISSUE THREAD

**Issue by ServicePal** [bootstrap-email/bootstrap-email#211]
### What version of Bootstrap Email are you using?

1.3.1

### How are you compiling?

Online Editor

### Code example

`<span class="badge badge-primary">Accepted</span>`

### Describe your issue

Output is
`            <table class="badge badge-primary" align="left" role="presentation" border="0" cellpadding="0" cellspacing="0">
              <tbody>
                <tr>
                  <td style="line-height: 1; font-size: 75%; display: inline-block; font-weight: 700; white-space: nowrap; border-radius: 4px; margin: 0; padding: 4px 6.4px;" align="center" valign="baseline">
                    <span>Accepted</span>
                  </td>
                </tr>
              </tbody>
            </table>`

No primary color applied. Is this a documentation bug perhaps, since none of the badge- classes' work. Instead, badges have to be constructed like this

`<span class="badge bg-primary text-white rounded">Accepted</span>`
`<span class="badge bg-primary text-white rounded-full px-4">Accepted</span>`

**Comment by stuyam** [comment]
Yeah I think you are correct that this is a documentation issue.

**Comment by ServicePal** [comment]
I plan to log another issue for alignment being ignored for badges, and that appears to be a bug.
