### ISSUE TITLE
URL encoding for code between handlebars

### ISSUE THREAD

**Issue by bernhardreisenberger** [bootstrap-email/bootstrap-email#243]
### What version of Bootstrap Email are you using?

1.4.0

### How are you compiling?

CLI

### Describe your issue

Hi.

Unfortunately, code between handlebars will be URL encoded when used in the href attribute of a link. Here is an example:

`bootstrap-email -s '<a href="{{ foo bar }}">Some Button</a>'`

results in having the link be represented with encoded characters e.g. %20

`<a href="{{%20foo%20bar%20}}" style="color: #0d6efd;">Some Button</a>`

The code between the handlebars should not be URL encoded. I found this ticket https://github.com/bootstrap-email/bootstrap-email/issues/184 mentioning a similar bug.
I would be glad, if someone could please fix this.

kind regards, Bernhard

**Comment by stuyam** [comment]
Looks like this has regressed, looking into this!

**Comment by stuyam** [comment]
This was related to newer versions of nokogiri, thanks for brining it to my attention! This is now fixed in the latest v1.4.1 release: https://github.com/bootstrap-email/bootstrap-email/releases/tag/1.4.1

**Comment by bernhardreisenberger** [comment]
thank you.
