### ISSUE TITLE
Encoding issue with RSpec on Rails 7

### ISSUE THREAD

**Issue by hendrix-7** [bootstrap-email/bootstrap-email#244]
### What version of Bootstrap Email are you using?

v1.1.4

### How are you compiling?

Rails

### Code example

On a mailer spec, it seems there is some encoding issue when we have accents at the body of the message:

```
require 'rails_helper'

RSpec.describe SignupMailer, type: :mailer do
  describe 'welcome' do
    let(:user) { create(:user, email: 'user@example.com') }
    let(:mail) { SignupMailer.welcome(user) }

    it 'renders the body' do
      expect(mail.body.encoded).to match('Seja bem vindo à Plataforma!')
    end  
end
```

BTW, it's portuguese here, meaning "Welcome to the Platform".
I am getting a `&#224;` charactere in place of the `à`.
The string `mail.body.encoded` shows the string like this:
`Boas vindas &#224; Platafor=\r\ma\r\n`

This issue also happens if I try to get the body through this alternative way:
`mail.html_part.body.decoded`
In this case, the string shows up a little less messed up, but still messed up:
`Boas vindas &#224; Plataforma\n`

### Describe your issue

Despite the issue with RSpec, the message gets generated just fine, and renders perfectly in the browser. 
And, looking at the page's source code, there's no sign of this issue, as the text appears perfectly clean as:
`Boas vindas à Plataforma`

I tried explicitly adding the `premailer-rails` at the Gemfile, to see if it's latest version could solve it. But it didn't. 
`gem 'premailer-rails'`

The only solution for now was to get this at the spec:

```
it 'renders the body' do
  decoded_body = ActionView::Base.full_sanitizer.sanitize(mail.html_part.body.decoded)
  expect(decoded_body).to match('Boas vindas à Plataforma!')
end
```

But it's a very ugly and gives the clue of something is wrong behind the scenes.  (here or at the gem)
Can you guys take a look on that?
Thanks!

BTW, here's what I am running here:
```
Rails 7.0.7.2, with Bootstrap + esbuild
ruby 3.1.4p223

```

**Comment by hendrix-7** [comment]
Complementing: i've just created a fresh new rails app, and could confirm that the issue really exists, I mean, it's not something about my current project. 

The mailer spec was passing smoothly, testing accented matches, but as soon as I installed the `bootstrap-email` gem, the issue appeared exactly as described above.

**Comment by hendrix-7** [comment]
PS: it doesn't happen with accents in the `subject`, only in the `body`. 

```
# spec/mailers/ideas_mailer.rb
require "rails_helper"

RSpec.describe IdeasMailer, type: :mailer do
  describe "notify_new_comment" do
    let(:mail) { IdeasMailer.notify_new_comment }

    it "renders the headers" do
      expect(mail.subject).to eq("Olá do Bootstrap Email") # Works just fine
      expect(mail.to).to eq(["to@example.org"])
      expect(mail.from).to eq(["from@example.com"])
    end

    it "renders the body" do
      # expect(mail.body.encoded).to match("Olá, coração!") # Fails
      decoded_body = Nokogiri::HTML.parse(mail.body.encoded).text
      expect(decoded_body).to match("Olá, coração!")
    end
  end
end
```

**Comment by hendrix-7** [comment]
Hi there, did anyone have a chance to take a look on this one?

**Comment by stuyam** [comment]
Unfortunately this is the expected result. It is bootstrap email not premailer. We have to do a lot of tricky encoding work to fix some issues with emails rendered in apple mail. Therefore things are encoded to html entities often. I would just suggest accounting for it in your tests like you did.
