### ISSUE TITLE
@media query does not work

### ISSUE THREAD

**Issue by cybernetix-belgrade** [bootstrap-email/bootstrap-email#31]
You should put **&lt;meta content="width=device-width, initial-scale=1" name="viewport" /&gt;** by default in online editor, otherwise @media query does not work

**Comment by stuyam** [comment]
Coming soon to the new online editor...

**Comment by stuyam** [comment]
Bootstrap email now detects if there are missing meta tags such as this viewport tag and with automatically insert one into the head of the document. Added in v1.1.0
