### ISSUE TITLE
Anchor Image Issue

### ISSUE THREAD

**Issue by dougroutledge** [bootstrap-email/bootstrap-email#49]
Images are not clickable with anchor tag put around them, after conversion using the render button on the site. https://bootstrapemail.com/editor

**Comment by dougroutledge** [comment]
<a href="https://www.bridgeoc.com/about/hiring.html"><img src="https://www.bridgeoc.com/about/images/jointeam.jpg" class="img-fluid p-1" /></a>

Forgot a tag example

**Comment by dougroutledge** [comment]
` <a href="https://www.bridgeoc.com/about/hiring.html"><img src="https://www.bridgeoc.com/about/images/jointeam.jpg" class="img-fluid p-1" /></a>`

**Comment by slovenski08** [comment]
same problem.  rendered code comes out with the a tag totally separated from the image tag:

`<table class="card-body" border="0" cellpadding="0" cellspacing="0" style="font-family: Helvetica, Arial, sans-serif; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; border-collapse: collapse; width: 100%;">
  <tbody>
    <tr>
      <td style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 16px; width: 100%; margin: 0; padding: 20px;" align="left">
        <div>
      <a href="https://www.slovenskicamps.com" style="color: #4A5167;"></a><table class="mx-auto" align="center" border="0" cellpadding="0" cellspacing="0" style="font-family: Helvetica, Arial, sans-serif; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; border-collapse: collapse; margin: 0 auto;">
  <tbody>
    <tr>
      <td style="border-spacing: 0px; border-collapse: collapse; line-height: 24px; font-size: 16px; margin: 0;" align="left">
        <img class="" width="100" height="100" src="https://www.slovenskicamps.com/static/images/logo-web.png" style="height: auto; line-height: 100%; outline: none; text-decoration: none; border: 0 none;">
      </td>
    </tr>
  </tbody>
</table>`

**Comment by WoodyDark** [comment]
Hi guys, is there a fix for this yet? I'm running version 0.3.1 and still facing this issue

**Comment by WoodyDark** [comment]
It seems like there's a similar issue discussion in https://github.com/stuyam/bootstrap-email/issues/15 and there's a somewhat feasible [workaround](https://github.com/stuyam/bootstrap-email/issues/15#issuecomment-628563709l) in case anyone is interested.

**Comment by stuyam** [comment]
Just tested this in the latest bootstrap email release v1.1.2 and it seems to work fine now 👍
