### ISSUE TITLE
iOS Mail just displays garbage 

### ISSUE THREAD

**Issue by kallsbo** [bootstrap-email/bootstrap-email#50]
This works great with the exception for iOS built in mail app. It renders as seen in the picture below.
Trying to troubleshoot this I came across character limits that might effect the iOS mail app. Each line should be a maximum of 78 characters long and no more then 998 continuous characters.

I narrowed it down to the style tag in the head. If removed it renders OK in iOS mail but off course not in any of the other mail applications. Tried to run a unminify on the css with the same result.

Any ideas? 

![image](https://user-images.githubusercontent.com/5733456/67739052-622cc500-fa11-11e9-8058-5d4cff0366f7.png)

**Comment by kallsbo** [comment]
Did some more digging into this and it seems to be the @media yahoo section. If you cut that in half or remove a large chunk of the classes in it everything renders OK. Can't really see why but that's as far as I got.

**Comment by ahaverty** [comment]
Just to add, we're seeing the exact same issues only in the iOS mail client.

**Comment by ahaverty** [comment]
@kallsbo Our garbage emails are identical in characters. I couldn't get your last comment's workaround to work. Did you add that css to application-mailer.scss? Did you fill in the `// CSS Here` with actual css or is this to prevent any css from rendering? Have you also still got the yahoo media workaround in? If so, can you explain how you did that.
Thanks!

**Comment by stuyam** [comment]
This seems like an issue people are seeing, I wonder if it is a new problem in iOS 13, would be happy to accept a pull request of suggestions of how we can fix this!

**Comment by kallsbo** [comment]
@ahaverty I use the online editor so I just added those three to the styles tag in the output. But you have to remove the // CSS Here and just leave it blank.

@stuyam I would love to put one in but I don't ruby that well. Thanks for a great implementation by the way!

**Comment by ahaverty** [comment]
@kallsbo Sorry, I don't understand the fix. Adding that css doesn't seem to prevent the problem for me. I'm not sure what "online editor" is. Do you know what exactly is causing the problem? I investigated the character count and ran my emails through email validators, and couldn't find any issues 🤔 
@stuyam that would be my guess too, although this was the only issue I could find on the web about it.

**Comment by kallsbo** [comment]
@ahaverty I use this: https://bootstrapemail.com/editor I added the three empty selectors just before the </style> tag in the finished code. Exactly why this occurs is a mystery to me. I checked all the character counts and standard stuff like that and came up short as well.

**Comment by ahaverty** [comment]
Really odd. What was your reasoning when you discovered that fix? I could understand if there was some css that we were trying to override, but if I understand CSS, this is changing nothing in the style 🤔

**Comment by kallsbo** [comment]
The reasoning was that this worked in another e-mail template. So just to make sure it wasn't an issue with this I tried to add it and the problem went away.

**Comment by ahaverty** [comment]
@stuyam I'm discovering the same text across the internet from different forums dating back awhile. It seems like ios mail client is perhaps detecting an unusual encoding.
See here, which matches our characters, but isn't an email issue:
https://stackoverflow.com/questions/11933866/asp-net-404-response-text-chinese-like/12038364#12038364

**Comment by ahaverty** [comment]
I've put in a bit of time trying to figure this out. Everything seems ok to me, including the encoding tags. I think we're going to revert to non-html emails or non bootstrap styled emails for now. @stuyam have you heard if this is happening for anyone else? Or any suggestions on what else we could try? Cheers

**Comment by ahaverty** [comment]
I've tested this on ios 13 which has the issue, but also tested on an ipad and iphone on ios 10, and they are working as expected.

**Comment by ahaverty** [comment]
This will sound ridiculous, but I was scrolling through some weird outlook forums, and found a suggestion to add a wingdings character to the email.
I don't usually go down the route of trying random fixes, but as I was grasping for straws, I gave it a shot..

Adding a wingding character to the body of my emails prevents the strange characters/encoding for iOS13. I am able to reproduce it working and not working without wingdings.

@stuyam I have very little experience with email, but perhaps you could explain this workaround to me? 😅

**Comment by ahaverty** [comment]
Just to clarify, I added the following (hidden so that our users don't have to relive the 80's).
`<div style="display: none;">&#10175;</div>`

**Comment by ahaverty** [comment]
I found the forum, it was actually an apple forum thread from 2013 https://discussions.apple.com/thread/5117624

**Comment by Solomon04** [comment]
Also facing this issue. Literally only on the iOS mail client.

**Comment by stuyam** [comment]
Just catching up on this. Has anyone been able to fix this for their own project? Is it an encoding thing?

**Comment by ahaverty** [comment]
@stuyam not "fixed" but see my later comments for a workaround. That might help with uncovering what the issue really is?

**Comment by saulocoutinho** [comment]
@ahaverty, the wingding workaround worked on my project.

**Comment by ahaverty** [comment]
@saulocoutinho and do you feel weird inside like I do? 😅

**Comment by ghiculescu** [comment]
> Just to clarify, I added the following (hidden so that our users don't have to relive the 80's).
> `<div style="display: none;">&#10175;</div>`

This fixed things for me too. Guessing it forces the encoding on the email to be correct.

Before:
![image](https://user-images.githubusercontent.com/509837/108555171-c0428300-72ba-11eb-9949-5b9d71982e4a.png)

After:
![image](https://user-images.githubusercontent.com/509837/108555144-b751b180-72ba-11eb-9def-643d46d2ebc1.png)

**Comment by stuyam** [comment]
I am working on fixing this is Bootstrap Email 1.0. Does anyone have an example email that this is happening in that they can reproduce when sending to Apple Mail that they would be willing to share with me to test? Or know what characters or symbols to use to reliably reproduce this in Bootstrap Email. Maybe @ahaverty or @ghiculescu? Thanks 🙏

**Comment by ghiculescu** [comment]
Yep. I can send you one. Where should I email it to?

**Comment by stuyam** [comment]
That would be great @ghiculescu you can send it to stu@stuyam.com, just attach it as an html file so I get the exact html and not something post processed by my email provider. 🙏  thank you.

**Comment by ghiculescu** [comment]
@stuyam sorry for the delay, just sent that email now.

**Comment by jeremybdk** [comment]
Just you need to be careful, don't add this at the beginning of your email as it will be displayed in the iOS Mail preview.

**Comment by ComtelJeremy** [comment]
Just an anecdotal experience here... We had this issue pop up and it had to do with a &copy; symbol being pasted into an e-mail, not `&copy;`. Changing the character to `&copy;` resolved it for us.

**Comment by stuyam** [comment]
I believe this is actually fixed in v1 now! 🎉 was a lot of troubleshooting: Fixed in [v1](https://github.com/bootstrap-email/bootstrap-email/releases/tag/1.0.0)
