### ISSUE TITLE
Font-Family:unset und M$ Outlook

### ISSUE THREAD

**Issue by Multithread** [bootstrap-email/bootstrap-email#57]
Commit [f2156f10f787eb915fb6553f6d707cb6febdff6a](https://github.com/stuyam/bootstrap-email/commit/f2156f10f787eb915fb6553f6d707cb6febdff6a) #43 creates an issue with Microsoft Outlook clients.
You are unable to set a Font, when the spezific commit does "font-family:unset".

I would advice to undo it, until a solution can be found.

**Comment by stuyam** [comment]
Do you have an example of what happens in those cases? What does it do? What does it look like?

**Comment by Multithread** [comment]
Without font-family:unset:
![image](https://user-images.githubusercontent.com/9254339/71907382-3003b600-316c-11ea-8c4d-3b555213012c.png)

With font-family: unset:
![image](https://user-images.githubusercontent.com/9254339/71907398-398d1e00-316c-11ea-9aeb-245c3e702e1f.png)


Template:
<div class="container">
  <br>
  <div class="card mb-4 borderCard" >
    <div class="card-body">
      <h1>Test</h1>
    </div>
  </div>
</div>

Css:
.borderCard{
border-top:5px solid rgb(81,87,155); 
font-family:"Comic Sans MS", "Comic Sans";
padding-left:40px;
}

**Comment by stuyam** [comment]
Fixed in [v1](https://github.com/bootstrap-email/bootstrap-email/releases/tag/1.0.0)
