### ISSUE TITLE
Doesn't work with disabled text mail generation

### ISSUE THREAD

**Issue by ch000** [bootstrap-email/bootstrap-email#64]
When disabling premailers text mail generation via:

`Premailer::Rails.config.merge!(generate_text_part: false)`

`make_bootstrap_mail` throws an exception, that it can't access the `body` method in: https://github.com/stuyam/bootstrap-email/blob/c2685fd3e31ffd114390069dad5e7d34c50f7c0d/lib/bootstrap-email.rb#L48

**Comment by stuyam** [comment]
This is fixed in v1+
