### ISSUE TITLE
Feature Request: No "click to open in web browser" message for outlook

### ISSUE THREAD

**Issue by blubbll** [bootstrap-email/bootstrap-email#69]
Whenever i ran a template and sent it to outlook, it displayed that message right under the receipients.

`<meta name="ProgId" content="Word.Document">`

worked for me to hide it.

**Comment by stuyam** [comment]
Could you give some more details about what you are looking for here? Do you have a before and after screenshot you could share of what this meta tag does? Thanks!

**Comment by blubbll** [comment]
I cannot post screens from my workplace, but this is what it looks like in like all Outlook Versions:

https://answers.microsoft.com/en-us/office/forum/office_2013_release-outlook/outlook-2013-email-displyas-like-a-mobile-phone/bc5ffc21-51b0-4f90-a625-da41c56202ef?page=4

It basically is a hyperlink to a local mht file (outlook-ready htmlemail format).

The html displys correctly.

If i add the meta tag to the header manually via the editor, it works without the additional message and it looks like it should.

If i remove it again, the "warning" appears again.

This may be useful for people who work with Outlook to have this being included by default or you could at least add an template-side or app-side option that says "improve compatibility with Desktop Outlook".

**Comment by stuyam** [comment]
Outside of the current scope of the project but a good option if people want this feature. Ultimately I don't think it's necessarily a bad message if something doesn't look 100% in Outlook
