### ISSUE TITLE
"Rerender" does not work

### ISSUE THREAD

**Issue by adnannrajaa** [bootstrap-email/bootstrap-email#72]
![image](https://user-images.githubusercontent.com/58033249/94269188-bdd03d00-ff57-11ea-9a21-f700959d3e68.png)

**Comment by stuyam** [comment]
Is this the current editor? If so, give a try to the new beta editor coming soon at https://editor.bootstrapemail.com you should have better luck with that.

**Comment by adnannrajaa** [comment]
Thanks for the response. 
yeah its the current editor. I am trying to use it today but facing the above error.

**Comment by stuyam** [comment]
The beta editor is pretty stable, I would use that linked above.

**Comment by adnannrajaa** [comment]
![image](https://user-images.githubusercontent.com/58033249/94277711-5e782a00-ff63-11ea-9235-df76287f8d59.png)

where should I find "Code or Preview" button in this link https://editor.bootstrapemail.com

**Comment by stuyam** [comment]
Click the "HTML" tab at the top.

**Comment by adnannrajaa** [comment]
Thanks its help me a lot.

**Comment by stuyam** [comment]
I'll leave this issue open until the new editor is _released_ so people have an option.

**Comment by adnannrajaa** [comment]
ok
