### ISSUE TITLE
MSO Desktop/Mobile Classes Causing Duplicated Content

### ISSUE THREAD

**Issue by jlpeterman** [bootstrap-email/bootstrap-email#92]
### Describe the problem:

Not sure if I'm missing something here, but tested using the .d-dekstop and .d-mobile classes to show/hide content for mobile and desktop on an email, and ran into issues with content being shown on desktop versions, regardless of the class, in MSO 2007, 2010, 2013, 2017, 2019 -- 2003 seemed to work correctly -- See duplicated headline in screenshot

![Screen Shot 2021-03-07 at 4 58 35 PM](https://user-images.githubusercontent.com/42424158/110262014-1c6a0000-7f67-11eb-82c8-d81ca3c6fbe1.png)

**Comment by stuyam** [comment]
Fixed in [v1](https://github.com/bootstrap-email/bootstrap-email/releases/tag/1.0.0)
