### ISSUE TITLE
Online Editor HTML view overlaying code while scrolling

### ISSUE THREAD

**Issue by EyMaddis** [bootstrap-email/bootstrap-email#93]
This bug is best shown:

https://user-images.githubusercontent.com/1409100/110311032-8506ba80-8003-11eb-9c32-be3851e56f8f.mp4

MacOS 11.2.1 (20D74)
Google Chrome Version 88.0.4324.192

**Comment by stuyam** [comment]
Thanks for the bug report, hoping to get this fixed soon as Ill be doing some small updates to the editor.

**Comment by stuyam** [comment]
Fixed 🎉
