### ISSUE TITLE
NoMethodError: undefined method `bootstrap_mail'

### ISSUE THREAD

**Issue by harssh** [bootstrap-email/bootstrap-email#95]
### Describe the problem:

bootstrap_mail is undefined 

 bundle info rails          
  * rails (5.2.4)
        Summary: Full-stack web application framework.
        Homepage: http://rubyonrails.org
        Path: /.rvm/gems/ruby-2.6.6/gems/rails-5.2.4

bundle info bootstrap-email  
  * bootstrap-email (1.0.0.alpha1.2)
        Summary: Bootstrap 5 stylesheet, compiler, and inliner for responsive and consistent emails with the Bootstrap syntax you know and love. Support: command line, ruby, rails
        Homepage: https://bootstrapemail.com
        Path: /.rvm/gems/ruby-2.6.6gems/bootstrap-email-1.0.0.alpha1.2

All the steps were followed from https://v1.bootstrapemail.com/docs/setup#ruby-on-rails
Do let me know if you need more details.

**Comment by stuyam** [comment]
Yeah there is a bug in the alpha. However it is now fixed on the master branch but not yet released. There will likely be an alpha 2 released this weekend. For now you can use this in your gemfile to pull master:
```ruby
gem 'bootstrap-email', git: 'https://github.com/bootstrap-email/bootstrap-email.git'
```

I'll post here again once the latest alpha is out just to close the loop but master should work for you for the time being. Thank you for testing and let me know if you experience any more issues 👍

**Comment by stuyam** [comment]
New alpha released: https://github.com/bootstrap-email/bootstrap-email/releases/tag/1.0.0.alpha2
